# Generated by Django 4.2.6 on 2023-11-01 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_profile_phone_no_user_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_no',
            new_name='phone',
        ),
    ]
