# Generated by Django 4.2.6 on 2023-11-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_phone_no_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compTitle', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=20)),
                ('subCity', models.CharField(max_length=20)),
                ('landmark', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=300)),
                ('region', models.CharField(max_length=20)),
                ('compType', models.CharField(max_length=20)),
                ('compSev', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CompTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
