# Generated by Django 4.2.6 on 2023-11-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='username',
            field=models.CharField(default='t1', max_length=100),
            preserve_default=False,
        ),
    ]
